테스트 진행후 변경사항 반영

diff --git a/setup/bindir/mold-update-dbpassword.in b/setup/bindir/mold-update-dbpassword.in
--- a/setup/bindir/mold-update-dbpassword.in
+++ b/setup/bindir/mold-update-dbpassword.in
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
@@ -120,7 +120,7 @@ do
   read -s newpass_check
   echo " "
 
-  if [ "$pass" != "$newpass_check" ] || [ -z $pass ] || [ ${#pass} -lt 4 ]
+  if [ "$newpass" != "$newpass_check" ] || [ -z $newpass ] || [ ${#newpass} -lt 8 ]
   then
     echo "Please check your new DB password again.(more than 8 characters)"
   else
@@ -128,6 +128,38 @@ do
   fi
 done
 
+
+
+
+curDbCloudEncPassword=$(sed '/^\#/d' $DB_FILE | grep 'db.cloud.password'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'i | sed 's/^ENC(\(.*\))/\1/' | sed 's/\//\\\\\//g')
+curDbUsageEncPassword=$(sed '/^\#/d' $DB_FILE | grep 'db.usage.password'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'i | sed 's/^ENC(\(.*\))/\1/' | sed 's/\//\\\\\//g')
+encVersion=$(sed '/^\#/d' /etc/cloudstack/management/db.properties | grep 'db.cloud.encryptor.version'  | tail -n 1 | cut -d "=" -f2-)
+
+key=$(cat key)
+if [ ! $key == "" ]
+then
+  newDbCloudEncPassword=(`java -classpath $jarfile com.cloud.utils.crypt.EncryptionCLI -i "$newpass" -p "$key" $encVersion`)
+  newDbUsageEncPassword=(`java -classpath $jarfile com.cloud.utils.crypt.EncryptionCLI -i "$newpass" -p "$key" $encVersion`)
+  if [ ! $newDbCloudEncPassword ] || [ ! $newDbUsageEncPassword ]
+  then
+    echo "Failed to encrypt DB password" | tee -a $LOGFILE
+    failed 9 
+  else
+    echo "curDbCloudEncPassword :: "$curDbCloudEncPassword
+    echo "newDbCloudEncPassword :: "$newDbCloudEncPassword
+    echo "curDbUsageEncPassword :: "$curDbUsageEncPassword
+    echo "newDbUsageEncPassword :: "$newDbUsageEncPassword
+    sed -i "s/$curDbCloudEncPassword/$newDbCloudEncPassword/g" $DB_FILE
+    sed -i "s/$curDbUsageEncPassword/$newDbUsageEncPassword/g" $DB_FILE
+    res=$?
+    if [ $res -eq 0 ];then
+      echo "DB properties root, cloud password change completed" | tee -a $LOGFILE
+    else
+      echo "DB properties root, cloud password change failed"| tee -a $LOGFILE
+      exit 1
+    fi
+  fi
+fi
 
 echo "::::: Enter the current DB root password.. :::::"
 echo -n "Root Password : "
@@ -139,30 +171,11 @@ mysql -uroot -p$rootdbpass -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$new
 
 res=$?
 if [ $res -eq 0 ];then
-   echo "mysql root, cloud password change completed" | tee -a $LOGFILE
+   echo "Mysql root, cloud password change completed" | tee -a $LOGFILE
 else
-   echo "mysql root, cloud password change failed"| tee -a $LOGFILE
+   echo "Mysql root, cloud password change failed"| tee -a $LOGFILE
    exit 1
 fi
-
-curDbCloudEncPassword=$(sed '/^\#/d' $DB_FILE | grep 'db.cloud.password'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'i | sed 's/^ENC(\(.*\))/\1/')
-curDbUsageEncPassword=$(sed '/^\#/d' $DB_FILE | grep 'db.usage.password'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'i | sed 's/^ENC(\(.*\))/\1/')
-
-key=$(cat key)
-if [ ! $key == "" ]
-then
-  newDbCloudEncPassword=(`java -classpath $jarfile com.cloud.utils.crypt.EncryptionCLI -i "$newpass" -p "$key" V2`)
-  newDbUsageEncPassword=(`java -classpath $jarfile com.cloud.utils.crypt.EncryptionCLI -i "$newpass" -p "$key" V2`)
-  if [ ! $newDbCloudEncPassword ] || [ ! $newDbUsageEncPassword ]
-  then
-    echo "Failed to encrypt DB password" | tee -a $LOGFILE
-    failed 9 
-  else
-    sed -i 's/'$curDbCloudEncPassword'/'$newDbCloudEncPassword'/g' $DB_FILE
-    sed -i 's/'$curDbUsageEncPassword'/'$newDbUsageEncPassword'/g' $DB_FILE
-  fi
-fi
-
 
 rm -rf key
 key=010101010101010101
@@ -171,6 +184,6 @@ key=010010101001000110
 key=111101011101101001
 key=001001001111001110
 
-echo "The DB password change procedure has been set up properly."
+echo "DB password change has been completed."
 
-exit $res
+exit 0
